### PR TITLE
Fix/ Tab issue when user menu is closed

### PR DESCRIPTION
**Pull request by R-Cloud-Designs**
#### Hey Team,

I've implemented some updates that mirror the approach we took in [PR #11](https://github.com/Videodock/ott-web-app/pull/11). These enhancements are focused on improving accessibility across our components. Here's a brief overview:

#### Changes:
1. **Enhancements to the Header Component**:
   - We've improved accessibility in the `IconButton` component by adding `aria-controls` and `aria-expanded`. This helps screen readers understand the state and context of the user menu.

2. **Updates to MenuButton and UserMenu**:
   - The `MenuButton` now includes `onBlur` and `onFocus` event handlers. These additions aid in managing the opening and closing of the UserMenu.

This PR relates to [OTT-486
](https://videodock.atlassian.net/browse/OTT-486)

#### Request for Review:
These are relatively small yet significant changes that enhance the accessibility of our application.

### CODE REVIEW

**Review by langemike — APPROVED** [review]
Really nice! Already approved (before the PR description is provided) ;) I also tested it locally myself within my desktop browser.

**Review by MelissaDTH — APPROVED** [review]
Looks good!

**Comment by royschut** [comment]
I doubt if it's a stable approach to keep switching between true/false based on focus/blur events. You could run into race conditions. I'm thinking about an alternative approach, but wanted to say it meanwhile.

**Review by royschut — APPROVED** [review]
Nice!

**Pull request merged**
