### PR TITLE
Feat / favicons in different sizes

### PR DESCRIPTION
**Pull request by langemike**
This change creates icons in different image sizes.

To generate custom images in different image sizes you should replace` packages/theme/assets/app-icon.png` and then run:
```bash
cd platform/web && yarn generate-pwa-assets
```

When putting the source icon somewhere outside the working directory, eg within `packages/themes` , it will not create a *.ico file. Therefore I have chosen to place it in less preferable `platforms/web/public/images`.

I also wanted to dynamically render the `<link>` tags but using the [API](https://vite-pwa-org.netlify.app/assets-generator/api#api ) with `generateHtmlMarkup` was quite a challenge which got a lot of hurdles. So I finally chosen to hard-code them.

I put `sharp` inside `optionalDependencies`, even though it is required by `@vite-pwa/assets-generator` to generate the images. Because when I put it `devDependencies` I will get a unused dep warning.

Changes:
- [x] Automate create icons in different image sizes [OTT-663](https://videodock.atlassian.net/browse/OTT-663)
- [x] Render `<link>` tags with more icon sizes for broad compatibility [OTT-662](https://videodock.atlassian.net/browse/OTT-662)
- [x] Remove deprecated HTML for MSIE and Windows Phones [OTT-668](https://videodock.atlassian.net/browse/OTT-668)
- [x] Dynamically create `manifest.json` [OTT-664](https://videodock.atlassian.net/browse/OTT-664) - Separate PR: https://github.com/Videodock/ott-web-app/pull/53

[OTT-663]: https://videodock.atlassian.net/browse/OTT-663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OTT-662]: https://videodock.atlassian.net/browse/OTT-662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OTT-668]: https://videodock.atlassian.net/browse/OTT-668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by ChristiaanScheermeijer — APPROVED** [review]
Nice work! 

You can add 'sharp' to the `./platforms/web/.depcheckrc.yaml` and add a comment it is required by `pwa-asset-generated`.

Do the `-i ./index.html` and `-m ./public/manifest.json` parameters not work directly?

**Review by royschut — APPROVED** [review]
Nice Mike!
I have 2 questions/considerations: 
- Should we add a little description to the documentation?
- I find it a bit counter-intuitive to have the image generation plugin from `/web`, while the images should potentially be for any platform. But I think we have no choice, since we're using Vite and web is the only package that uses it. How do we see this?

**Comment by langemike** [comment]
> Do the -i ./index.html and -m ./public/manifest.json parameters not work directly?

No. This is not how it works. I believe this could be Vite specific CLI options. Here is an overview of the `pwa-assets-generator `CLI options: https://vite-pwa-org.netlify.app/assets-generator/cli.html#options

> Should we add a little description to the documentation?

I agree.  I put it on the list to discuss next OTT sprint 3, because I was afraid putting it somewhere, can lead to discussions by itself. See discussion list: https://videodock.atlassian.net/wiki/spaces/OTT/pages/2577858562/OTT+Sprint+2024-3#To-discuss

> I find it a bit counter-intuitive to have the image generation plugin from /web, while the images should potentially be for any platform.

Currently it is indeed only targeted to web. Maybe we should re-add the package again within `platforms/capacitor`. Yes that is repetative, but we should use a different config (image sizes) and output directories (ios and android). I'm unsure if it will encapsulate all icon requirements of Android and iOs, though. Something for later?

**Comment by royschut** [comment]
Yes okay Mike! Let's merge :-)

**Pull request merged**
