### PR TITLE
Refactor / form fields and control elements

### PR DESCRIPTION
**Pull request by ChristiaanScheermeijer**
## Description

- This PR introduces new `Input`, `Select`, `FormField` and `Checkbox` components
- Unifies form field labels, aria attributes and helper text in the `FromField` component
- Removes the “(Optional)“ marking from custom components for fields that are not required
- Adds an asterisks `*` to a field if it is required and ensures `aria-hidden="true"` is applied
  - The e2e test _'The Sign up modal will invalidate upon submit only if a value is inputted'_ is removed due to the fact that it is corrected in this PR: [GitHub test file](https://github.com/jwplayer/ott-web-app/blob/64c1b8a2a5f7bfdeb151e1df2949746b318eb6e3/platforms/web/test-e2e/tests/register_test.ts#L69C1-L70C1)
- Solves: OTT-1261

This PR is based on this previously approved #105 PR

### Steps completed:

According to our definition of done, I have completed the following steps:

- [x] Acceptance criteria met
- [x] Unit tests added
- [ ] Docs updated (including config and env variables)
- [ ] Translations added
- [x] UX tested
- [x] Browsers / platforms tested
- [x] Rebased & ready to merge without conflicts
- [x] Reviewed own code

### CODE REVIEW

**Comment by MelissaDTH** [comment]
@ChristiaanScheermeijer, can you also take another look at this PR (specifically to the description, maybe we need to explain more about the refactor?)

**Comment by ChristiaanScheermeijer** [comment]
@MelissaDTH I think we can submit this to the open source repo 🎉

**Review by royschut — APPROVED** [review]
🦬

**Review by langemike — APPROVED** [review]
Nice work, Chris!

**Comment by MelissaDTH** [comment]
Is merged in `jw-ott-web-app` repo, therefore closed

**Pull request closed without merging**
