### PR TITLE
Fix / Footer links and apply aria-pressed to password icon

### PR DESCRIPTION
**Pull request by MelissaDTH**
## This PR

- Implements `aria-pressed` to the password icon **|| OTT-1068**
- Applies an underline to all footer links **|| OTT-1006**

### CODE REVIEW

**Review by ChristiaanScheermeijer — APPROVED** [review]

**Review by langemike — COMMENTED** [review]
I strongly believe that if we use `aria-pressed` the toggled `aria-label` should be discarded (same as the add/remove favorite button). Both ARIA attributes should not be combined.

I found official documentation which backups my statement:

> Do not change the contents of the label on a toggle when the state changes. If a button label says "pause", do not change it to "play" when pressed. In this example, when the pressed state is true, the label remains "Pause" so a screen reader would say something like "Pause toggle button pressed".

Link: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-pressed

I think we should also do this for the favorite (add/remove) while we at it [OTT-1044](https://videodock.atlassian.net/browse/OTT-1044)

Do you agree?

**Comment by royschut** [comment]
> I strongly believe that if we use `aria-pressed` the toggled `aria-label` should be discarded (same as the add/remove favorite button). Both ARIA attributes should not be combined.

I'm reading the same, I agree with Mike.
So perhaps we should do:

```javascript
<IconButton
  aria-label={t('account.view_password')}
  onClick={toggleViewPassword}
  aria-pressed={viewPassword}
>
```

**Comment by MelissaDTH** [comment]
After internal discussion, we've reached a consensus to keep the `aria-label`. Because without it, the screen reader provides limited context, only saying 'ticked' or 'unticked' without any additional context.

**Review by langemike — APPROVED** [review]
Nice accessibility improvements! Let's wait untill all e2e succeed and then merge!

**Review by royschut — APPROVED** [review]

**Pull request merged**
