### PR TITLE
Feat / Update role of buttons and small html structure tweaks

### PR DESCRIPTION
**Pull request by MelissaDTH**
## This PR

- Applies the missing role `submit` to the corresponding buttons || [OTT-402](https://videodock.atlassian.net/browse/OTT-402)
- Moves the related videos element found on the Inline Player page to correct the HTML DOM order || [OTT-479](https://videodock.atlassian.net/browse/OTT-479)
- Also moves the hidden header on the Account page || [OTT-530](https://videodock.atlassian.net/browse/OTT-530)

[OTT-402]: https://videodock.atlassian.net/browse/OTT-402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OTT-479]: https://videodock.atlassian.net/browse/OTT-479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OTT-530]: https://videodock.atlassian.net/browse/OTT-530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by R-Cloud-Designs** [comment]
@MelissaDTH LGTM, nice work.

**Review by royschut — APPROVED** [review]
Good stuff!

**Review by R-Cloud-Designs — APPROVED** [review]

**Review by langemike — CHANGES_REQUESTED** [review]
Unfortunately I have to disapprove this. Details will follow. Do not merge yet ;)

**Comment by langemike** [comment]
We're almost there! I found two issues....

1. Submit buttons needs to be placed inside the `<form>`
Screenshot 2024-01-25 at 10 17 57

That is currently not the case for Profile Info. I could not find it in other situations.. But they could potentially also exist

2. Logical heading order
When looking at [Account.test.tsx.snap](https://github.com/Videodock/ott-web-app/pull/47/files#diff-bb275644d55a2e45f652026a2b7857709725342144580d832dcd0c112a059632) it seems like the `<h1>` is placed outside the `<section>`. But when I preview the page I don't see that... I don't know the cause.. I hope you are able to spot this!
Screenshot 2024-01-25 at 10 21 00

**Comment by MelissaDTH** [comment]
@langemike, thanks for your feedback!

1. I've updated the submit button to be inside the `form` element in my latest commit like so:

Screenshot 2024-01-25 at 14 27 39

2. I'm not sure that you were looking at the right branch/code, because the hidden `h1` element is correctly placed above the `section` element and only occurs once, see:

Screenshot 2024-01-25 at 14 22 25

**Comment by langemike** [comment]
> looking at the right branch/code

The ServiceWorker is quite aggressive locally. I see it now. Sorry for the confusion!

All work approved!

**Review by langemike — APPROVED** [review]

**Pull request merged**
