### PR TITLE
Chore / add pr deployment previews workflows

### PR DESCRIPTION
**Pull request by VincentCouzij**
Add workflow file for deployment previews

### CODE REVIEW

**Comment by langemike** [comment]
Can we maybe post the deployment preview URL as a comment in the PR? I'm a little bit lazy 😅
Suggestion: https://stackoverflow.com/a/64126737

~I assume currently we need to manually type in the deployment URL. Am I correct? It's not that difficult, but to click an URL will be even nicer~

I found the button! Not needed!

**Comment by VincentCouzij** [comment]
> Can we maybe post the deployment preview URL as a comment in the PR? I'm a little bit lazy 😅 Suggestion: https://stackoverflow.com/a/64126737
> 
> I assume currently we need to manually type in the deployment URL. Am I correct? It's not that difficult, but to click an URL will be even nicer

Check the button next to the deployment message "View deployment" that takes you to the correct url

**Review by langemike — APPROVED** [review]
handy!

**Review by MelissaDTH — APPROVED** [review]
Very happy with this!

**Pull request merged**
